Add preliminary single-instance support for drop-down mode
lxqt/qterminal pull request #1115
Opened 2024-04-25 17:15 UTC by marcusbritanicus

This PR adds preliminary support for single instance mode for drop-down mode. Additionally, it adds support for toggling the drop-down instance via `qterminal -d` command line. On wayland, we can simply add a command-binding pair for most compositors. On wayfire, this would simply be adding the following lines under the `[command]` section.

```
binding_qterminal_dd: KEY_F12
command_qterminal_dd: qterminal -d
```

If an instance of qterminal in the drop-down mode exists, it will toggle it. Otherwise, a new drop-down instance will be created. The normal qterminal instances are unaffected.

This fixes both #1028 and #1059. Since it's not possible to fix one without the other, I am breaking the one-issue-one-PR rule.

![snapshot](https://github.com/lxqt/qterminal/assets/3350667/dc909ed4-fae9-448c-88cf-3d8c8ba1f299)

Cc: @yan12125 @stefonarch @tsujan

2024-04-25 18:22 UTC, stefonarch requested changes

2024-04-25 18:22 UTC, stefonarch commented on CMakeLists.txt
> +set(SHELLQT_MINIMUM_VERSION "6.0.0")
A leftover from the layershell PR

2024-04-25 18:22 UTC, stefonarch commented on CMakeLists.txt
> +find_package(LayerShellQt ${SHELLQT_MINIMUM_VERSION} REQUIRED)
Same

2024-04-25 18:22 UTC, stefonarch commented on CMakeLists.txt
> +    LayerShellQtInterface
Same

2024-04-26 05:43 UTC, marcusbritanicus commented on CMakeLists.txt
> +set(SHELLQT_MINIMUM_VERSION "6.0.0")
Thanks. It's fixed now.

2024-04-26 06:11 UTC, stefonarch commented
Works as it should - for me GTM

2024-05-03 12:10 UTC, tsujan commented
I'll review it after QTerminal 2.0 is released.

2024-05-20 18:33 UTC, tsujan commented
Although this code seems OK, I'm afraid not only a D-Bus-based single instance needs much less code (because D-Bus is already used), but also it's more reliable than the socket-lock method (I say that based on my experience with old versions of FeatherPad).

Here is the D-Bus-based PR: https://github.com/lxqt/qterminal/pull/1131

2024-05-21 07:03 UTC, marcusbritanicus commented
@tsujan Just tested #1131. It works great!! I'll close this.

2024-05-21 07:03 UTC, closed without merging

2024-05-21 07:48 UTC, stefonarch commented
Works ok here too, but thanks to @marcusbritanicus 's code which made it already possible to have it for the last weeks ;)